// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyfpdugeureovfmmlsfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5ZnBkdWdldXJlb3ZmbW1sc2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5NjY5MTMsImV4cCI6MjA1MzU0MjkxM30.6SvGRswBTudf2gg0ef5aV8ZtR85w7bqsVLPJhBGRQwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);